version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@biomejs/biome" # new biome version fails ci when it tries to validate against $schema field
