[package]
name = "oxicache-client"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TCP client for oxicache"

[[bin]]
name = "oxicache-cli"
path = "src/main.rs"

[dependencies]
oxicache-wire.workspace = true
bytes.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
thiserror.workspace = true
clap = { version = "4", features = ["derive", "env"] }
serde = "1"
rmp-serde = "1"
rmpv = { version = "1", features = ["with-serde"] }

[dev-dependencies]
oxicache-server = { path = "../server" }
serde = { version = "1", features = ["derive"] }
